[theme]
primaryColor = "#E63946" # Loun l'asasi dyalk (les boutons, les sélections)
backgroundColor = "#F1FAEE" # Loun dyal lkhalfia l'asasiya
secondaryBackgroundColor = "#A8DADC" # Loun dyal l'menu li f jnb (sidebar)
textColor = "#1D3557"
font = "sans serif"